---
version: 0.1.0-dev

matrix:
  run:
    # - # Execution 1: LandCoverAI w/ AutoEncoder
    #   dataset: LandCoverAI
    #   model: AutoEncoder

    # - # Execution 2: LandCoverAI w/ DCGAN discriminator
    #   dataset: LandCoverAI
    #   model: DCGANDiscriminator

    # - # Execution 3: LandCoverAI w/ izi architecture
    #   dataset: LandCoverAI
    #   model: Izi

    # - # Execution 4: LandCoverAI w/ ziz architecture
    #   dataset: LandCoverAI
    #   model: Ziz

    - # Execution 4: LandCoverAI w/ ziz architecture
      dataset: LandCoverAI
      model: BiGAN

datasets:
  - name: LandCoverAI
    folder: 'data/download/LandCoverAI'
    params:
      processed_folder: 'data/processed/LandCoverAI'


models:
  - name: AutoEncoder
    src: 'src/aerial_anomaly_detection/models/autoencoder.py:AutoEncoder'
    params:
      latent_dimension: 1000
      img_width: 32
      img_height: 32
      pretrained_weights: weights/autoencoder.pth

  - name: DCGANDiscriminator
    src: 'src/aerial_anomaly_detection/models/utils/dcgan_discriminator.py:Discriminator'
    params:
      img_width: 32
      img_height: 32
      pretrained_weights: 'runs/DCGAN/LandCoverAI/train/epoch_200/discriminator.pth'

  - name: Izi
    src: 'src/aerial_anomaly_detection/models/izi.py:Izi'
    params:
      latent_dimension: 1000
      img_width: 32
      img_height: 32
      pretrained_decoder_weights_path: 'models/DCGAN/generator.pth'
      pretrained_weights: weights/izi.pth

  - name: Ziz
    src: 'src/aerial_anomaly_detection/models/ziz.py:Ziz'
    params:
      latent_dimension: 1000
      img_width: 32
      img_height: 32
      pretrained_decoder_weights_path: 'models/DCGAN/generator.pth'
      pretrained_weights: weights/ziz.pth

  - name: BiGAN
    src: 'src/aerial_anomaly_detection/models/bigan.py:BiGAN'
    params:
      latent_dimension: 1000
      img_width: 32
      img_height: 32
      pretrained_encoder_weights_path: 'models/BiGAN/encoder.pth'
      pretrained_generator_weights_path: 'models/BiGAN/generator.pth'
      pretrained_discriminator_weights_path: 'models/BiGAN/discriminator.pth'

params:
  run_folder: 'runs'
  batch_size: 256
  n_epochs: 200

jobs:
  - name: Preprocess LandCover.ai dataset
    dataset: LandCoverAI
    steps:

      - name: Setup LandCover.ai dataset
        python-module: aerial_anomaly_detection.preprocess.setup.landcover_ai
        if:
          not_file: '{dataset.params.processed_folder}/scene_index.csv'

      - name: Scene tiling
        python-module: aerial_anomaly_detection.preprocess.tile.landcover_ai
        params:
          tile_width: 32
          tile_height: 32
          tile_x_step: 32
          tile_y_step: 32
          test_tiles_per_type_and_scene: 100
        if:
          not_file: '{dataset.params.processed_folder}/tile_index.csv'

      - name: Tile partitioning
        python-module: aerial_anomaly_detection.preprocess.partition.landcover_ai
        params:
          train_pct: 0.8

  - name: Train DCGAN
    dataset: LandCoverAI
    steps:
    - name: DCGAN Training
      python-module: aerial_anomaly_detection.train.landcover_ai_dcgan
      params:
        out_folder: '{run_folder}/DCGAN/{dataset.name}/train'
        pretrained_weights: 'runs/DCGAN/LandCoverAI/train/epoch_190'
        latent_dimension: 1000
        img_width: 32
        img_height: 32
        n_epochs: 10
        start_epoch: 191
        epochs_per_save: 10
        num_evaluation_images: 64
        learning_rate: 0.0001

  - name: Train BiGAN components
    dataset: LandCoverAI
    steps:
    - name: BiGAN Training
      python-module: aerial_anomaly_detection.train.landcover_ai_bigan
      params:
        out_folder: '{run_folder}/BiGAN/{dataset.name}/train'
        pretrained_weights: 'runs/BiGAN/LandCoverAI/train/epoch_190'
        latent_dimension: 1000
        img_width: 32
        img_height: 32
        n_epochs: 10
        start_epoch: 191
        epochs_per_save: 10
        num_evaluation_images: 64
        learning_rate: 0.0001

  - name: Train anomaly detectors
    dataset: '{matrix.run.dataset}'
    model: '{matrix.run.model}'
    params:
      out_folder: '{run_folder}/{model.name}/{dataset.name}/train'
    steps:
      - name: Generic model training
        python-module: aerial_anomaly_detection.train.train_model
        params:
          learning_rate: 0.0001

  - name: Evaluation
    dataset: '{matrix.run.dataset}'
    model: '{matrix.run.model}'
    params:
      out_folder: '{run_folder}/{model.name}/{dataset.name}/inference'
    steps:
      - name: Generic model evaluation
        python-module: aerial_anomaly_detection.evaluation.evaluate_model
        params:
          tile_width: 32
          tile_height: 32
          tile_x_step: 32
          tile_y_step: 32
        if:
          not_file: '{out_folder}/global_metrics.csv'