---
version: 0.1.0-dev

matrix:
  run:
    - # Execution 1: LandCoverAI
      dataset: LandCoverAI

datasets:
  - name: LandCoverAI
    folder: 'data/download/LandCoverAI'
    params:
      processed_folder: 'data/processed/LandCoverAI'


models:
  - name: AutoEncoder
    src: 'src/aerial_anomaly_detection/models/autoencoder.py:AutoEncoder'
    params:
      latent_dimension: 1000
      img_width: 32
      img_height: 32
      model_weights: models/AutoEncoder/model.pth

params:
  run_folder: 'runs'
  batch_size: 256
  n_epochs: 200

jobs:
  - name: Preprocess LandCover.ai dataset
    dataset: LandCoverAI
    steps:

      - name: Setup LandCover.ai dataset
        python-module: aerial_anomaly_detection.preprocess.setup.landcover_ai
        if:
          not_file: '{dataset.params.processed_folder}/scene_index.csv'

      - name: Scene tiling
        python-module: aerial_anomaly_detection.preprocess.tile.landcover_ai
        params:
          tile_width: 32
          tile_height: 32
          tile_x_step: 32
          tile_y_step: 32
          test_tiles_per_type_and_scene: 100
        if:
          not_file: '{dataset.params.processed_folder}/tile_index.csv'

      - name: Tile partitioning
        python-module: aerial_anomaly_detection.preprocess.partition.landcover_ai
        params:
          train_pct: 0.8

  - name: Train
    params:
      out_folder: models
    steps:
      - name: Train Convolutional AutoEncoder
        python-module: aerial_anomaly_detection.train.autoencoder_landcover_ai
        dataset: LandCoverAI
        model: AutoEncoder
        params:
          learning_rate: 0.0001

  - name: Evaluation
    params:
      base_out_folder: runs
    steps:
      - name: Evaluate Convolutional AutoEncoder
        python-module: aerial_anomaly_detection.evaluation.landcover_ai.autoencoder
        dataset: LandCoverAI
        model: AutoEncoder
        params:
          out_folder: '{base_out_folder}/{model.name}'
          tile_width: 32
          tile_height: 32
          tile_x_step: 32
          tile_y_step: 32
        if:
          not_file: '{out_folder}/global_metrics.csv'